/* This file is generated by the MEMFS Converter */
#ifndef _MEMFS_sample_H_
#define _MEMFS_sample_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "memfs.h"

extern const m_table sample_table[];
extern const uint8_t sample_data[];
extern const uint8_t _binary_sample_data_bin_start[];

#ifdef MEMFS_IMPLEMENTATION

const m_table sample_table[]={
  {29,	4,	0,	"."}, // 0
  {17,	2,	0,	"sample"}, // 1
  {12,	5,	0,	"images"}, // 2
  {8,	4,	0,	"images01"}, // 3
  {5,	0,	19286,	"img01.jpg"}, // 4
  {6,	19288,	43783,	"img02.jpg"}, // 5
  {7,	63072,	32175,	"img03.jpg"}, // 6
  {8,	95248,	27344,	"img04.jpg"}, // 7
  {9,	122592,	19286,	"img01.jpg"}, // 8
  {10,	141880,	43783,	"img02.jpg"}, // 9
  {11,	185664,	32175,	"img03.jpg"}, // 10
  {12,	217840,	27344,	"img04.jpg"}, // 11
  {17,	4,	0,	"images00"}, // 12
  {14,	245184,	19286,	"img01.jpg"}, // 13
  {15,	264472,	43783,	"img02.jpg"}, // 14
  {16,	308256,	32175,	"img03.jpg"}, // 15
  {17,	340432,	27344,	"img04.jpg"}, // 16
  {27,	5,	0,	"images"}, // 17
  {23,	4,	0,	"images01"}, // 18
  {20,	367776,	19286,	"img01.jpg"}, // 19
  {21,	387064,	43783,	"img02.jpg"}, // 20
  {22,	430848,	32175,	"img03.jpg"}, // 21
  {23,	463024,	27344,	"img04.jpg"}, // 22
  {24,	490368,	19286,	"img01.jpg"}, // 23
  {25,	509656,	43783,	"img02.jpg"}, // 24
  {26,	553440,	32175,	"img03.jpg"}, // 25
  {27,	585616,	27344,	"img04.jpg"}, // 26
  {28,	612960,	43783,	"img02.jpg"}, // 27
  {29,	656744,	32175,	"img03.jpg"}, // 28
};
#endif //MEMFS_IMPLEMENTATION
#ifdef __cplusplus
} // extern "C"
#endif
#endif //_MEMFS_sample_H_
